name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Efetuar o login no docker hub
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORT }}
    - name: Construir a imagem de container
      run: 
    - name: Enviar a imagem para o docker registry
      run:
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: Autenticar na AWS
      run: 
    - name: COnfigurar o KubeConfig
      run: 
    - name: Aplicar o deploy
      run: 
      
